#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-qtconsole
Version  : 5.4.3
Release  : 85
URL      : https://files.pythonhosted.org/packages/6f/6c/0e20886d4024f8b0dec690f2be0206dbad3abab9b87fc90fba8b990c720a/qtconsole-5.4.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/6f/6c/0e20886d4024f8b0dec690f2be0206dbad3abab9b87fc90fba8b990c720a/qtconsole-5.4.3.tar.gz
Summary  : Jupyter Qt console
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-qtconsole-bin = %{version}-%{release}
Requires: pypi-qtconsole-license = %{version}-%{release}
Requires: pypi-qtconsole-python = %{version}-%{release}
Requires: pypi-qtconsole-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(ipykernel)
BuildRequires : pypi(ipython_genutils)
BuildRequires : pypi(jupyter_client)
BuildRequires : pypi(jupyter_core)
BuildRequires : pypi(packaging)
BuildRequires : pypi(pygments)
BuildRequires : pypi(pyzmq)
BuildRequires : pypi(qtpy)
BuildRequires : pypi(traitlets)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Jupyter QtConsole
![Windows tests](https://github.com/jupyter/qtconsole/workflows/Windows%20tests/badge.svg)
![Macos tests](https://github.com/jupyter/qtconsole/workflows/Macos%20tests/badge.svg)
![Linux tests](https://github.com/jupyter/qtconsole/workflows/Linux%20tests/badge.svg)
[![Coverage Status](https://coveralls.io/repos/github/jupyter/qtconsole/badge.svg?branch=master)](https://coveralls.io/github/jupyter/qtconsole?branch=master)
[![Documentation Status](https://readthedocs.org/projects/qtconsole/badge/?version=stable)](https://qtconsole.readthedocs.io/en/stable/)
[![Google Group](https://img.shields.io/badge/-Google%20Group-lightgrey.svg)](https://groups.google.com/forum/#!forum/jupyter)

%package bin
Summary: bin components for the pypi-qtconsole package.
Group: Binaries
Requires: pypi-qtconsole-license = %{version}-%{release}

%description bin
bin components for the pypi-qtconsole package.


%package license
Summary: license components for the pypi-qtconsole package.
Group: Default

%description license
license components for the pypi-qtconsole package.


%package python
Summary: python components for the pypi-qtconsole package.
Group: Default
Requires: pypi-qtconsole-python3 = %{version}-%{release}

%description python
python components for the pypi-qtconsole package.


%package python3
Summary: python3 components for the pypi-qtconsole package.
Group: Default
Requires: python3-core
Provides: pypi(qtconsole)
Requires: pypi(ipykernel)
Requires: pypi(ipython_genutils)
Requires: pypi(jupyter_client)
Requires: pypi(jupyter_core)
Requires: pypi(packaging)
Requires: pypi(pygments)
Requires: pypi(pyzmq)
Requires: pypi(qtpy)
Requires: pypi(traitlets)

%description python3
python3 components for the pypi-qtconsole package.


%prep
%setup -q -n qtconsole-5.4.3
cd %{_builddir}/qtconsole-5.4.3
pushd ..
cp -a qtconsole-5.4.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1684611664
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-qtconsole
cp %{_builddir}/qtconsole-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-qtconsole/6b85326e6a68c099bbfa0e2c7d5ca15aa9763753 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-qtconsole

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-qtconsole/6b85326e6a68c099bbfa0e2c7d5ca15aa9763753

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
